### ISSUE TITLE
Question: Can precommit.hook run implicitly?

### ISSUE THREAD

**Issue by lovato** [collin5/precommit-hook#19]
My question is because when I used hooks on NodeJS, just by installing the package, repo is already hooked. So you don't need to manually do this for every repo you clone.
This would prevent developers to forget configuring the hook.

Is there any objection to this kind of procedure? I mean, if you install it as a local dependency, it's because you want to setup hooks, right?
This is the package I am talking about: https://www.npmjs.com/package/pre-commit

**Comment by lovato** [comment]
I didn't even notice that.
Is this an answer?
https://stackoverflow.com/questions/17806485/execute-a-python-script-post-install-using-distutils-setuptools#18159969

**Comment by lovato** [comment]
I did some research, and to me, looks like the problem was the local working directory.
Everything was doing fine, on the wrong dir ... /tmp/<something>-build/.git/hooks, instead of on the real folder.
I am not saying my code solves "the problem", and that is absolutely resilient. Probably it is not.
But with that change, I was able to after install, have the hook installed.

**Comment by lovato** [comment]
#20

**Comment by lovato** [comment]
It is not resilient because you need to be on the root of your project, or else, it will be creating .git folders... I personally would not touch user data... If there is no .git folder, raise an error.

**Comment by collin5** [comment]
Right, we should probably let users do `git init` themselves and just raise an exception if one tries to add hook to a non-git directory [ I think the code that does this is here https://github.com/collin5/precommit-hook/blob/ef43332177e332cd6728b409f4a51a12fb7fd844/app/scripts.py#L18 ]. Could you please be willing to take this up. Thanks.

**Comment by lovato** [comment]
My pleasure! Can you check #22 ?

**Comment by collin5** [comment]
Thank you! taking a look at it.

**Comment by lovato** [comment]
Well, after checking #22, which would be probably merged, do you have plans to release it to Pypi? :smirk:
I need to start using this new version... :smile:

**Comment by collin5** [comment]
Yeah going to push it to PyPI asap. Thank you 👍

**Comment by lovato** [comment]
@collin5 
One thing: I think README now needs a minor update, since hooks get installed automatically.

**Comment by collin5** [comment]
Pushed to PyPI but looks like this still only works when you install from `tar.gz` or `git url`. Post install still doesn't run when you install from PyPI. Not sure why but I think we may still be missing something 😔 .

**Comment by lovato** [comment]
Let me help... 

Another thing: if you go to https://pypi.org/project/precommit-hook/, readme is messed up. This happens sometimes to my projects.

**Comment by lovato** [comment]
There is a pypi-dev to where you can publish packages too, and if they are good, you can publish to the main one. I did it on my old project https://github.com/lovato/machete/blob/develop/.travis.yml

**Comment by lovato** [comment]
A few options: https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools/36902139#36902139

I cant tell that this will make a difference, but in the examples, install.run(self) is the last line.

**Comment by lovato** [comment]
Another approach.
Download https://files.pythonhosted.org/packages/60/25/bda5449839ecaaf4cbe6c7a376c594159c6730674394e93e743702ce5922/precommit_hook-0.1.8-py2.py3-none-any.whl

Then do a `pip install precommit_hook-0.1.8-py2.py3-none-any.whl`
It will not work too. This is a easy way to debug.

**Comment by lovato** [comment]
Just to mention, my old project from 2015 was deployed as tar.gz
https://pypi.org/project/machete/#files

**Comment by lovato** [comment]
https://packaging.python.org/discussions/wheel-vs-egg/

**Comment by lovato** [comment]
Just tested... not sure how you generate the packaging, but I was able to use python setup.py sdist to generate the egg file, and sdist_wheel to generate wheel one. Please note that the messed up readme can be caused by an older wheel package you may have installed. Also, for P3, there is this: https://github.com/lovato/precommit-hook/blob/release/setup.py#L32

**Comment by lovato** [comment]
Hi @collin5 , don't get mad at me, but I was really in the need of a package like this.
So today I decided to build one to fit my needs, it and was based on your project. I added all the credits there. If is there something else I can do for you, just ask.

https://pypi.org/project/hooks4git
https://github.com/lovato/hooks4git

**Comment by lovato** [comment]
Please, close this issue after you read this.

**Comment by collin5** [comment]
No worries 🙂 
Sorry for late response, been kinda busy lately. Still looking at options you suggested above and will try some of them anytime soon. Thank you!
